name: My first pipeline
on: [push]

jobs:
  build: 
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: java setup
      uses: actions/setup-java@v3
      with:
        java-version: '11'
    - name: maven build
      run: mvn --batch-mode --update-snapshots verify
    - run: ls
    - name: testing the GitHub cicd
      run: |
        echo "This is my first pipeline"
    
   
